name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install gtest manually
      run: sudo apt-get update && sudo apt-get install g++ && sudo apt-get install make && sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/lib
    
    - name: Make directory and build
      run: make
      
    - name: Test
      run: bin/test
